/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.tms.service;
import cn.zhuatech.tms.common.BusinessException;import cn.zhuatech.tms.dto.TmsDto.*;import cn.zhuatech.tms.model.*;import cn.zhuatech.tms.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.LocalDateTime;import java.time.format.DateTimeFormatter;import java.util.List;
@Service @Transactional(readOnly=true) public class TmsService {
    private final TransportOrderRepository orders;private final DriverRepository drivers;private final VehicleRepository vehicles;private final TrackingEventRepository events;
    public TmsService(TransportOrderRepository orders,DriverRepository drivers,VehicleRepository vehicles,TrackingEventRepository events){this.orders=orders;this.drivers=drivers;this.vehicles=vehicles;this.events=events;}
    public Dashboard dashboard(){var all=orders.findAllByOrderByPlannedPickupAtAsc();BigDecimal freight=all.stream().map(TransportOrder::getFreightAmount).filter(v->v!=null).reduce(BigDecimal.ZERO,BigDecimal::add);return new Dashboard(all.size(),orders.countByStatus("运输中"),orders.countByStatus("待调度"),orders.countByStatus("运输异常"),vehicles.findAll().stream().filter(v->"可调度".equals(v.getStatus())).count(),freight,all.stream().filter(o->!"普通".equals(o.getPriority())&&!"已签收".equals(o.getStatus())).limit(5).map(OrderView::from).toList());}
    public List<OrderView> orders(){return orders.findAllByOrderByPlannedPickupAtAsc().stream().map(OrderView::from).toList();}
    public List<DriverView> drivers(){return drivers.findAll().stream().map(DriverView::from).toList();}
    public List<VehicleView> vehicles(){return vehicles.findAll().stream().map(VehicleView::from).toList();}
    public List<TrackingView> tracking(Long orderId){return events.findByTransportOrderIdOrderByEventTimeDesc(orderId).stream().map(TrackingView::from).toList();}
    @Transactional public OrderView create(CreateOrderRequest r){String no="TO-"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"));var order=new TransportOrder(no,r.customerName(),r.origin(),r.destination(),r.cargoName(),r.weightTons(),r.volumeCbm(),r.plannedPickupAt(),r.plannedDeliveryAt(),"待调度",r.priority(),r.freightAmount());orders.save(order);events.save(new TrackingEvent(order,LocalDateTime.now(),r.origin(),"订单创建","运输订单已创建，等待调度"));return OrderView.from(order);}
    @Transactional public OrderView dispatch(Long id,DispatchRequest r){var order=order(id);var driver=drivers.findById(r.driverId()).orElseThrow(()->new BusinessException("司机不存在"));var vehicle=vehicles.findById(r.vehicleId()).orElseThrow(()->new BusinessException("车辆不存在"));if(!"可调度".equals(driver.getStatus())||!"可调度".equals(vehicle.getStatus()))throw new BusinessException("司机或车辆当前不可调度");order.dispatch(driver,vehicle);events.save(new TrackingEvent(order,LocalDateTime.now(),order.getOrigin(),"调度完成","已分配司机 "+driver.getName()+" 与车辆 "+vehicle.getPlateNo()));return OrderView.from(order);}
    @Transactional public OrderView updateStatus(Long id,StatusRequest r){var order=order(id);order.updateStatus(r.status());if(order.getVehicle()!=null)order.getVehicle().setCurrentPosition(r.location());events.save(new TrackingEvent(order,LocalDateTime.now(),r.location(),r.status(),r.remark()==null?r.status():r.remark()));return OrderView.from(order);}
    @Transactional public OrderView sign(Long id,SignRequest r){var order=order(id);order.sign("收货人："+r.receiver()+"；"+r.remark());events.save(new TrackingEvent(order,LocalDateTime.now(),r.location(),"签收完成",order.getProofRemark()));return OrderView.from(order);}
    private TransportOrder order(Long id){return orders.findById(id).orElseThrow(()->new BusinessException("运输订单不存在"));}
}
