/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.tms.controller;
import cn.zhuatech.tms.common.ApiResponse;import cn.zhuatech.tms.dto.TmsDto.*;import cn.zhuatech.tms.service.TmsService;import jakarta.validation.Valid;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.util.List;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/driver") @PreAuthorize("hasAnyRole('DRIVER','ADMIN')") public class DriverTaskController {private final TmsService service;/**
                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                  */
public DriverTaskController(TmsService service){this.service=service;}/**
                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                        */
@GetMapping("/tasks") public ApiResponse<List<OrderView>> tasks(){return ApiResponse.ok(service.orders());}/**
                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                   */
@PostMapping("/tasks/{id}/status") public ApiResponse<OrderView> status(@PathVariable Long id,@Valid @RequestBody StatusRequest request){return ApiResponse.ok("运输状态已更新",service.updateStatus(id,request));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
@PostMapping("/tasks/{id}/sign") public ApiResponse<OrderView> sign(@PathVariable Long id,@Valid @RequestBody SignRequest request){return ApiResponse.ok("签收回单已提交",service.sign(id,request));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@GetMapping("/tasks/{id}/tracking") public ApiResponse<List<TrackingView>> tracking(@PathVariable Long id){return ApiResponse.ok(service.tracking(id));}}
