/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.tms.controller;
import cn.zhuatech.tms.common.ApiResponse;import cn.zhuatech.tms.dto.TmsDto.*;import cn.zhuatech.tms.service.TmsService;import jakarta.validation.Valid;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.util.List;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/admin") @PreAuthorize("hasAnyRole('ADMIN','DISPATCHER')") public class TransportAdminController {private final TmsService service;/**
                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                         */
public TransportAdminController(TmsService service){this.service=service;}/**
                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                   */
@GetMapping("/dashboard") public ApiResponse<Dashboard> dashboard(){return ApiResponse.ok(service.dashboard());}/**
                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                   */
@GetMapping("/orders") public ApiResponse<List<OrderView>> orders(){return ApiResponse.ok(service.orders());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
@PostMapping("/orders") public ApiResponse<OrderView> create(@Valid @RequestBody CreateOrderRequest request){return ApiResponse.ok("运输订单已创建",service.create(request));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
@PostMapping("/orders/{id}/dispatch") public ApiResponse<OrderView> dispatch(@PathVariable Long id,@Valid @RequestBody DispatchRequest request){return ApiResponse.ok("调度成功",service.dispatch(id,request));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@GetMapping("/drivers") public ApiResponse<List<DriverView>> drivers(){return ApiResponse.ok(service.drivers());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@GetMapping("/vehicles") public ApiResponse<List<VehicleView>> vehicles(){return ApiResponse.ok(service.vehicles());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
@GetMapping("/orders/{id}/tracking") public ApiResponse<List<TrackingView>> tracking(@PathVariable Long id){return ApiResponse.ok(service.tracking(id));}}
